// src/types/analyse.ts

export type ActeurFields = {
  id?: string;
  label: string;
  nom?: string;
  prenom?: string;
  role?: string;
  lien?: string;
  qualite?: string;
  profession_brut?: string;
  statut_brut?: string;
  fonction?: string;
  domicile?: string;
  age?: string;
  sexe?: string;
  naissance_date?: string;
  deces_date?: string;
  est_vivant?: boolean | null;
  est_present?: boolean | null;
  pere_est_cite?: boolean | null;
  mere_est_citee?: boolean | null;
  a_signe?: boolean | null;
  note?: string;
  signature?: string;
  signature_libelle?: string;
};

export type ActeurEnrichiFields = ActeurFields & {
  acte_id?: string;
  source_table?: string;
  acte_label?: string;
  acte_date?: string;
  individu_id?: string;
  date_naissance_estimee?: string | null;
  lien_enrichi?: string | null;
};

export type Segment = {
  text: string;
  type: 'plain' | 'mention';
  entityId?: string;
  mentionId?: string;
};

export type Mention = {
  id: string;
  entite_id: string;
  bloc_id: string;
  start: number;
  end: number;
  preview: string;
  created_at?: string;
};

export type Entity = {
  id?: string;
  acte_id: string;
  categorie_id?: string | null;
  categorie?: any;
  label: string;
  mapping?: {
    cible_type: string;
    cible_id: string;
    acteur?: ActeurFields;
  };
  mentions?: Mention[];
  created_at?: string;
  updated_at?: string;
};

export const acteurFieldGroups = [
  {
    groupLabel: 'Rôle dans l’acte',
    fields: {
      role: 'lg-full',
    },
  },
  {
    groupLabel: 'Identité',
    fields: {
      qualite: 'lg-mid',
      qualite_ref: 'lg-mid',
      nom: 'lg-full',
      prenom: 'lg-full',
      est_nommee_par_nom_epoux: 'lg-mid',
    },
  },
  {
    groupLabel: 'Sexe',
    fields: {
      sexe: 'lg-mid',
    },
  },
  {
    groupLabel: 'Situation',
    fields: {
      situation_matrimoniale_ref: 'lg-mid',
      liens_matrimoniaux_ref: 'lg-full',
    },
  },
  {
    groupLabel: 'Âge & Vie',
    fields: {
      age: 'lg-mid',
      est_vivant: 'lg-mid',
    },
  },
  {
    groupLabel: 'Profession & Statut',
    fields: {
      profession_ref: 'lg-full',
      statut_proprietaire_ref: 'lg-mid',
      categorie_couleur_ref: 'lg-mid',
      statut_juridique_ref: 'lg-mid',
      situation_fiscale_ref: 'lg-mid',
      profession_brut: 'lg-mid',
      statut_brut: 'lg-mid',
      fonction: 'lg-full',
      titre_honneur: 'lg-full',
    },
  },
  {
    groupLabel: 'Filiation',
    fields: {
      filiation: 'lg-full',
      filiation_ref: 'lg-full',
      pere_est_cite: 'lg-mid',
      mere_est_citee: 'lg-mid',
    },
  },
  {
    groupLabel: 'Domicile & Origine',
    fields: {
      domicile_mention_toponyme: 'lg-full',
      domicile_brut: 'lg-full',
      domicile: 'lg-full',
      residence_mention_toponyme: 'lg-full',
      residence_brut: 'lg-full',
      origine_mention_toponyme: 'lg-full',
      origine_brut: 'lg-full',
      origine: 'lg-full',
    },
  },
  {
    groupLabel: 'Naissance - date et heure',
    fields: {
      naissance_date: 'lg-mid',
      naissance_heure: 'lg-mid',
    },
  },
  {
    groupLabel: 'Naissance - lieux',
    fields: {
      naissance_mention_toponyme: 'lg-full',
      naissance_lieu_brut: 'lg-full',
      naissance_lieux: 'lg-full',
      naissance_lieu_commune: 'lg-full',
      naissance_lieu_section: 'lg-mid',
      naissance_lieu_hameau: 'lg-mid',
      naissance_lieu_précisions: 'lg-full-textarea',
    },
  },
  {
    groupLabel: 'Décès - date et heure',
    fields: {
      deces_date: 'lg-mid',
      deces_heure: 'lg-mid',
    },
  },
  {
    groupLabel: 'Décès - lieux',
    fields: {
      deces_mention_toponyme: 'lg-full',
      deces_lieu_brut: 'lg-full',
      deces_lieux: 'lg-full',
      deces_lieu_commune: 'lg-full',
      deces_lieu_section: 'lg-mid',
      deces_lieu_hameau: 'lg-mid',
      deces_lieu_précisions: 'lg-full-textarea',
    },
  },
  {
    groupLabel: 'Lien avec l’acte',
    fields: {
      liens_non_matrimoniaux_ref: 'lg-full',
      lien: 'lg-full',
    },
  },
  {
    groupLabel: 'Déclarations',
    fields: {
      a_assiste_naissance: 'lg-mid',
      a_assiste_deces: 'lg-mid',
      est_declarant: 'lg-mid',
      est_present: 'lg-mid',
      est_consentant: 'lg-mid',
    },
  },
  {
    groupLabel: 'Signature',
    fields: {
      a_signe: 'lg-mid',
      signature: 'lg-mid',
      signature_ref: 'lg-mid',
      signature_libelle: 'lg-full',
    },
  },
  {
    groupLabel: 'Note',
    fields: {
      notes_ref: 'lg-full',
      note: 'lg-full-textarea',
    },
  },
  {
    groupLabel: 'Multi',
    fields: {
      multi: 'lg-full',
    },
  },
];

export const emptyActeur = Object.fromEntries(
  acteurFieldGroups.flatMap((group) => Object.keys(group.fields)).map((field) => [field, null]),
);

export const booleanChamps = [
  'est_nommee_par_nom_epoux',
  'est_vivant',
  'est_present',
  'est_consentant',
  'est_declarant',
  'a_assiste_naissance',
  'a_assiste_deces',
  'pere_est_cite',
  'mere_est_citee',
  'a_signe',
];

export const readonlyChamps = [
  'qualite',
  'filiation',
  'domicile',
  'origine',
  'naissance_lieux',
  'naissance_lieu_commune',
  'naissance_lieu_section',
  'naissance_lieu_hameau',
  'deces_lieux',
  'deces_lieu_commune',
  'deces_lieu_section',
  'deces_lieu_hameau',
  'signature'
];

export const champsParRole: Record<string, string[]> = {
  enfant: [
    'nom',
    'prenom',
    'sexe',
    'role',
    'filiation',
    'filiation_ref',
    'naissance_date',
    'naissance_mention_toponyme',
    'naissance_lieu_brut',
    'naissance_lieux',
    'naissance_lieu_commune',
    'naissance_lieu_section',
    'naissance_lieu_hameau',
    'naissance_lieu_précisions',
    'naissance_heure',
    'notes_ref',
    'note',
    'est_vivant',
    'pere_est_cite',
    'mere_est_citee',
  ],
  'enfant légitimé': [
    'nom',
    'prenom',
    'sexe',
    'age',
    'role',
    'filiation',
    'filiation_ref',
    'origine_mention_toponyme',
    'origine_brut',
    'origine',
    'naissance_date',
    'naissance_mention_toponyme',
    'naissance_lieu_brut',
    'naissance_lieux',
    'naissance_lieu_commune',
    'naissance_lieu_section',
    'naissance_lieu_hameau',
    'naissance_lieu_précisions',
    'naissance_heure',
    'notes_ref',
    'note',
    'est_vivant',
    'pere_est_cite',
    'mere_est_citee',
  ],
  père: [
    'nom',
    'prenom',
    'sexe',
    'age',
    'situation_matrimoniale_ref',
    'liens_matrimoniaux_ref',
    'qualite',
    'qualite_ref',
    'profession_ref',
    'profession_brut',
    'statut_brut',
    'statut_proprietaire_ref',
    'categorie_couleur_ref',
    'statut_juridique_ref',
    'situation_fiscale_ref',
    'fonction',
    'role',
    'domicile_mention_toponyme',
    'domicile_brut',
    'domicile',
    'residence_mention_toponyme',
    'residence_brut',
    'origine_mention_toponyme',
    'origine_brut',
    'origine',
    'signature',
    'signature_ref',
    'signature_libelle',
    'notes_ref',
    'note',
    'est_vivant',
    'est_present',
    'est_declarant',
    'a_signe',
  ],
  mère: [
    'nom',
    'prenom',
    'est_nommee_par_nom_epoux',
    'sexe',
    'situation_matrimoniale_ref',
    'liens_matrimoniaux_ref',
    'age',
    'qualite',
    'qualite_ref',
    'profession_ref',
    'profession_brut',
    'statut_brut',
    'statut_proprietaire_ref',
    'categorie_couleur_ref',
    'statut_juridique_ref',
    'situation_fiscale_ref',
    'fonction',
    'role',
    'domicile_mention_toponyme',
    'domicile_brut',
    'domicile',
    'residence_mention_toponyme',
    'residence_brut',
    'origine_mention_toponyme',
    'origine_brut',
    'origine',
    'signature',
    'signature_ref',
    'signature_libelle',
    'notes_ref',
    'note',
    'est_vivant',
    'est_present',
    'est_declarant',
    'a_signe',
  ],
  défunt: [
    'nom',
    'prenom',
    'est_nommee_par_nom_epoux',
    'sexe',
    'age',
    'situation_matrimoniale_ref',
    'liens_matrimoniaux_ref',
    'qualite',
    'qualite_ref',
    'profession_ref',
    'profession_brut',
    'statut_brut',
    'statut_proprietaire_ref',
    'categorie_couleur_ref',
    'statut_juridique_ref',
    'situation_fiscale_ref',
    'fonction',
    'role',
    'filiation',
    'filiation_ref',
    'domicile_mention_toponyme',
    'domicile_brut',
    'domicile',
    'residence_mention_toponyme',
    'residence_brut',
    'origine_mention_toponyme',
    'origine_brut',
    'origine',
    'lien',
    'liens_non_matrimoniaux_ref',
    'naissance_date',
    'naissance_mention_toponyme',
    'naissance_lieu_brut',
    'naissance_lieux',
    'naissance_lieu_commune',
    'deces_date',
    'deces_mention_toponyme',
    'deces_lieu_brut',
    'deces_lieux',
    'deces_heure',
    'deces_lieu_commune',
    'deces_lieu_section',
    'deces_lieu_hameau',
    'deces_lieu_précisions',
    'notes_ref',
    'note',
    'est_vivant',
    'pere_est_cite',
    'mere_est_citee',
  ],
  déclarant: [
    'nom',
    'prenom',
    'est_nommee_par_nom_epoux',
    'sexe',
    'age',
    'situation_matrimoniale_ref',
    'liens_matrimoniaux_ref',
    'qualite',
    'qualite_ref',
    'profession_ref',
    'profession_brut',
    'statut_brut',
    'statut_proprietaire_ref',
    'categorie_couleur_ref',
    'statut_juridique_ref',
    'situation_fiscale_ref',
    'fonction',
    'role',
    'domicile_mention_toponyme',
    'domicile_brut',
    'domicile',
    'residence_mention_toponyme',
    'residence_brut',
    'origine_mention_toponyme',
    'origine_brut',
    'origine',
    'lien',
    'liens_non_matrimoniaux_ref',
    'signature',
    'signature_ref',
    'signature_libelle',
    'notes_ref',
    'note',
    'est_vivant',
    'est_present',
    'est_declarant',
    'a_assiste_naissance',
    'a_signe',
  ],
  officier: [
    'nom',
    'prenom',
    'sexe',
    'qualite',
    'qualite_ref',
    'fonction',
    'role',
    'signature',
    'signature_ref',
    'signature_libelle',
    'notes_ref',
    'note',
    'est_vivant',
    'est_present',
    'a_signe',
  ],
  époux: [
    'nom',
    'prenom',
    'sexe',
    'age',
    'situation_matrimoniale_ref',
    'liens_matrimoniaux_ref',
    'qualite',
    'qualite_ref',
    'profession_ref',
    'profession_brut',
    'statut_brut',
    'statut_proprietaire_ref',
    'categorie_couleur_ref',
    'statut_juridique_ref',
    'situation_fiscale_ref',
    'fonction',
    'role',
    'filiation',
    'filiation_ref',
    'domicile_mention_toponyme',
    'domicile_brut',
    'domicile',
    'residence_mention_toponyme',
    'residence_brut',
    'origine_mention_toponyme',
    'origine_brut',
    'origine',
    'lien',
    'liens_non_matrimoniaux_ref',
    'naissance_date',
    'naissance_mention_toponyme',
    'naissance_lieu_brut',
    'naissance_lieux',
    'naissance_lieu_commune',
    'signature',
    'signature_ref',
    'signature_libelle',
    'notes_ref',
    'note',
    'est_vivant',
    'est_present',
    'pere_est_cite',
    'mere_est_citee',
    'a_signe',
  ],
  épouse: [
    'nom',
    'prenom',
    'est_nommee_par_nom_epoux',
    'sexe',
    'age',
    'situation_matrimoniale_ref',
    'liens_matrimoniaux_ref',
    'qualite',
    'qualite_ref',
    'profession_ref',
    'profession_brut',
    'statut_brut',
    'statut_proprietaire_ref',
    'categorie_couleur_ref',
    'statut_juridique_ref',
    'situation_fiscale_ref',
    'fonction',
    'role',
    'filiation',
    'filiation_ref',
    'domicile_mention_toponyme',
    'domicile_brut',
    'domicile',
    'residence_mention_toponyme',
    'residence_brut',
    'origine_mention_toponyme',
    'origine_brut',
    'origine',
    'lien',
    'liens_non_matrimoniaux_ref',
    'naissance_date',
    'naissance_mention_toponyme',
    'naissance_lieu_brut',
    'naissance_lieux',
    'naissance_lieu_commune',
    'signature',
    'signature_ref',
    'signature_libelle',
    'notes_ref',
    'note',
    'est_vivant',
    'est_present',
    'pere_est_cite',
    'mere_est_citee',
    'a_signe',
  ],
  'époux-père': [
    'nom',
    'prenom',
    'sexe',
    'age',
    'situation_matrimoniale_ref',
    'liens_matrimoniaux_ref',
    'qualite',
    'qualite_ref',
    'profession_ref',
    'profession_brut',
    'statut_brut',
    'statut_proprietaire_ref',
    'categorie_couleur_ref',
    'statut_juridique_ref',
    'situation_fiscale_ref',
    'fonction',
    'role',
    'domicile_mention_toponyme',
    'domicile_brut',
    'domicile',
    'residence_mention_toponyme',
    'residence_brut',
    'origine_mention_toponyme',
    'origine_brut',
    'origine',
    'deces_date',
    'deces_mention_toponyme',
    'deces_lieu_brut',
    'deces_lieux',
    'deces_heure',
    'deces_lieu_commune',
    'signature',
    'signature_ref',
    'signature_libelle',
    'notes_ref',
    'note',
    'est_vivant',
    'est_present',
    'est_consentant',
    'a_signe',
  ],
  'époux-mère': [
    'nom',
    'prenom',
    'est_nommee_par_nom_epoux',
    'sexe',
    'age',
    'situation_matrimoniale_ref',
    'liens_matrimoniaux_ref',
    'qualite',
    'qualite_ref',
    'profession_ref',
    'profession_brut',
    'statut_brut',
    'statut_proprietaire_ref',
    'categorie_couleur_ref',
    'statut_juridique_ref',
    'situation_fiscale_ref',
    'fonction',
    'role',
    'domicile_mention_toponyme',
    'domicile_brut',
    'domicile',
    'residence_mention_toponyme',
    'residence_brut',
    'origine_mention_toponyme',
    'origine_brut',
    'origine',
    'deces_date',
    'deces_mention_toponyme',
    'deces_lieu_brut',
    'deces_lieux',
    'deces_heure',
    'deces_lieu_commune',
    'signature',
    'signature_ref',
    'signature_libelle',
    'notes_ref',
    'note',
    'est_vivant',
    'est_present',
    'est_consentant',
    'a_signe',
  ],
  'épouse-père': [
    'nom',
    'prenom',
    'sexe',
    'age',
    'situation_matrimoniale_ref',
    'liens_matrimoniaux_ref',
    'qualite',
    'qualite_ref',
    'profession_ref',
    'profession_brut',
    'statut_brut',
    'statut_proprietaire_ref',
    'categorie_couleur_ref',
    'statut_juridique_ref',
    'situation_fiscale_ref',
    'fonction',
    'role',
    'domicile_mention_toponyme',
    'domicile_brut',
    'domicile',
    'residence_mention_toponyme',
    'residence_brut',
    'origine_mention_toponyme',
    'origine_brut',
    'origine',
    'deces_date',
    'deces_mention_toponyme',
    'deces_lieu_brut',
    'deces_lieux',
    'deces_heure',
    'deces_lieu_commune',
    'signature',
    'signature_ref',
    'signature_libelle',
    'notes_ref',
    'note',
    'est_vivant',
    'est_present',
    'est_consentant',
    'a_signe',
  ],
  'épouse-mère': [
    'nom',
    'prenom',
    'est_nommee_par_nom_epoux',
    'sexe',
    'age',
    'situation_matrimoniale_ref',
    'liens_matrimoniaux_ref',
    'qualite',
    'qualite_ref',
    'profession_ref',
    'profession_brut',
    'statut_brut',
    'statut_proprietaire_ref',
    'categorie_couleur_ref',
    'statut_juridique_ref',
    'situation_fiscale_ref',
    'fonction',
    'role',
    'domicile_mention_toponyme',
    'domicile_brut',
    'domicile',
    'residence_mention_toponyme',
    'residence_brut',
    'origine_mention_toponyme',
    'origine_brut',
    'origine',
    'deces_date',
    'deces_mention_toponyme',
    'deces_lieu_brut',
    'deces_lieux',
    'deces_heure',
    'deces_lieu_commune',
    'signature',
    'signature_ref',
    'signature_libelle',
    'notes_ref',
    'note',
    'est_vivant',
    'est_present',
    'est_consentant',
    'a_signe',
  ],
  'époux-tuteur': [
    'nom',
    'prenom',
    'sexe',
    'age',
    'situation_matrimoniale_ref',
    'liens_matrimoniaux_ref',
    'qualite',
    'qualite_ref',
    'profession_ref',
    'profession_brut',
    'statut_brut',
    'statut_proprietaire_ref',
    'categorie_couleur_ref',
    'statut_juridique_ref',
    'situation_fiscale_ref',
    'fonction',
    'role',
    'domicile_mention_toponyme',
    'domicile_brut',
    'domicile',
    'residence_mention_toponyme',
    'residence_brut',
    'origine_mention_toponyme',
    'origine_brut',
    'origine',
    'lien',
    'liens_non_matrimoniaux_ref',
    'signature',
    'signature_ref',
    'signature_libelle',
    'notes_ref',
    'note',
    'est_vivant',
    'est_present',
    'est_consentant',
    'a_signe',
  ],
  'épouse-tuteur': [
    'nom',
    'prenom',
    'est_nommee_par_nom_epoux',
    'sexe',
    'age',
    'situation_matrimoniale_ref',
    'liens_matrimoniaux_ref',
    'qualite',
    'qualite_ref',
    'profession_ref',
    'profession_brut',
    'statut_brut',
    'statut_proprietaire_ref',
    'categorie_couleur_ref',
    'statut_juridique_ref',
    'situation_fiscale_ref',
    'fonction',
    'role',
    'domicile_mention_toponyme',
    'domicile_brut',
    'domicile',
    'residence_mention_toponyme',
    'residence_brut',
    'origine_mention_toponyme',
    'origine_brut',
    'origine',
    'lien',
    'liens_non_matrimoniaux_ref',
    'signature',
    'signature_ref',
    'signature_libelle',
    'notes_ref',
    'note',
    'est_vivant',
    'est_present',
    'est_consentant',
    'a_signe',
  ],
  'témoin 1': [
    'nom',
    'prenom',
    'sexe',
    'age',
    'qualite',
    'qualite_ref',
    'profession_ref',
    'profession_brut',
    'statut_brut',
    'statut_proprietaire_ref',
    'categorie_couleur_ref',
    'statut_juridique_ref',
    'situation_fiscale_ref',
    'fonction',
    'role',
    'domicile_mention_toponyme',
    'domicile_brut',
    'domicile',
    'residence_mention_toponyme',
    'residence_brut',
    'origine_mention_toponyme',
    'origine_brut',
    'origine',
    'lien',
    'liens_non_matrimoniaux_ref',
    'signature',
    'signature_ref',
    'signature_libelle',
    'notes_ref',
    'note',
    'est_vivant',
    'est_present',
    'a_assiste_deces',
    'a_signe',
  ],
  'témoin 2': [
    'nom',
    'prenom',
    'sexe',
    'age',
    'qualite',
    'qualite_ref',
    'profession_ref',
    'profession_brut',
    'statut_brut',
    'statut_proprietaire_ref',
    'categorie_couleur_ref',
    'statut_juridique_ref',
    'situation_fiscale_ref',
    'fonction',
    'role',
    'domicile_mention_toponyme',
    'domicile_brut',
    'domicile',
    'residence_mention_toponyme',
    'residence_brut',
    'origine_mention_toponyme',
    'origine_brut',
    'origine',
    'lien',
    'liens_non_matrimoniaux_ref',
    'signature',
    'signature_ref',
    'signature_libelle',
    'notes_ref',
    'note',
    'est_vivant',
    'est_present',
    'a_assiste_deces',
    'a_signe',
  ],
  'témoin 3': [
    'nom',
    'prenom',
    'sexe',
    'age',
    'qualite',
    'qualite_ref',
    'profession_ref',
    'profession_brut',
    'statut_brut',
    'statut_proprietaire_ref',
    'categorie_couleur_ref',
    'statut_juridique_ref',
    'situation_fiscale_ref',
    'fonction',
    'role',
    'domicile_mention_toponyme',
    'domicile_brut',
    'domicile',
    'residence_mention_toponyme',
    'residence_brut',
    'origine_mention_toponyme',
    'origine_brut',
    'origine',
    'lien',
    'liens_non_matrimoniaux_ref',
    'signature',
    'signature_ref',
    'signature_libelle',
    'notes_ref',
    'note',
    'est_vivant',
    'est_present',
    'a_assiste_deces',
    'a_signe',
  ],
  'témoin 4': [
    'nom',
    'prenom',
    'sexe',
    'age',
    'qualite',
    'qualite_ref',
    'profession_ref',
    'profession_brut',
    'statut_brut',
    'statut_proprietaire_ref',
    'categorie_couleur_ref',
    'statut_juridique_ref',
    'situation_fiscale_ref',
    'fonction',
    'role',
    'domicile_mention_toponyme',
    'domicile_brut',
    'domicile',
    'residence_mention_toponyme',
    'residence_brut',
    'origine_mention_toponyme',
    'origine_brut',
    'origine',
    'lien',
    'liens_non_matrimoniaux_ref',
    'signature',
    'signature_ref',
    'signature_libelle',
    'notes_ref',
    'note',
    'est_vivant',
    'a_assiste_deces',
    'est_present',
    'a_signe',
  ],
  mention: [
    'nom',
    'prenom',
    'est_nommee_par_nom_epoux',
    'sexe',
    'situation_matrimoniale_ref',
    'liens_matrimoniaux_ref',
    'qualite',
    'qualite_ref',
    'role',
    'domicile_mention_toponyme',
    'domicile_brut',
    'domicile',
    'residence_mention_toponyme',
    'residence_brut',
    'lien',
    'liens_non_matrimoniaux_ref',
    'notes_ref',
    'note',
    'est_vivant',
  ],
  esclave: [
    'nom',
    'prenom',
    'sexe',
    'age',
    'qualite',
    'qualite_ref',
    'statut_brut',
    'categorie_couleur_ref',
    'statut_juridique_ref',
    'role',
    'notes_ref',
    'note',
    'est_vivant',
  ],
};

// regroupement des champs par section
export const sections: Record<string, { title: string; fields: string[] }> = {
  identite: {
    title: 'Identité',
    fields: [
      'est_nommee_par_nom_epoux',
      'qualite',
    'qualite_ref',
      'sexe',
      'age',
      'est_vivant',
      'profession_ref',
      'profession_brut',
      'statut_brut',
      'statut_proprietaire_ref',
      'categorie_couleur_ref',
      'statut_juridique_ref',
      'situation_fiscale_ref',
      'fonction',
      'titre_honneur',
    ],
  },
  localisation: {
    title: 'Localisation',
    fields: ['domicile_mention_toponyme', 'domicile', 'domicile_brut', 'residence_mention_toponyme','residence_brut', 'origine_mention_toponyme', 'origine', 'origine_brut'],
  },
  naissance: {
    title: 'Naissance',
    fields: [
      'naissance_date',
      'naissance_heure',
      'naissance_mention_toponyme',
      'naissance_lieu_brut',
      'naissance_lieux',
      'naissance_lieu_commune',
      'naissance_lieu_section',
      'naissance_lieu_hameau',
      'naissance_lieu_précisions',
    ],
  },
  deces: {
    title: 'Décès',
    fields: [
      'deces_date',
      'deces_heure',
      'deces_mention_toponyme',
      'deces_lieu_brut',
      'deces_lieux',
      'deces_lieu_commune',
      'deces_lieu_section',
      'deces_lieu_hameau',
      'deces_lieu_précisions',
    ],
  },
  entourage: {
    title: 'Entourage',
    fields: [
      'situation_matrimoniale_ref',
      'liens_matrimoniaux_ref',
      'lien',
      'liens_non_matrimoniaux_ref',
      'filiation',
      'filiation_ref',
      'pere_est_cite',
      'mere_est_citee',
    ],
  },
  statut: {
    title: 'Statut & Remarques',
    fields: [
      'est_present',
      'est_declarant',
      'a_assiste_naissance',
      'a_assiste_deces',
      'a_signe',
      'signature',
      'signature_ref',
      'signature_libelle',
      'notes_ref',
      'note',
    ],
  },
};
