export type TodoItemType = "todo" | "nice_to_have";

export type TodoItemStatus = "backlog" | "in_progress" | "done";

export type TodoItemPriority = "low" | "medium" | "high";

export type TodoItem = {
  id: string;
  label: string;
  type: TodoItemType;
  status: TodoItemStatus;
  expectedAt?: string; // YYYY-MM-DD
  done?: boolean;

  filePath?: string;
  details?: string[];
  category?: string;
  priority?: TodoItemPriority;
};

export const TODO_ITEMS: TodoItem[] = [
  {
    id: "story-direct-link-gromer",
    label: "Créer un écran plus propre pour expliciter le lien direct avec Gromèr",
    type: "todo",
    status: "in_progress",
    expectedAt: "2026-04-05",
    filePath: "src/features/family-tree/pages/FamilyRelationshipStoryPage.tsx",
    category: "family-tree",
    priority: "medium",
    details: ["Voir mon lien avec Gromèr", "Rendre l’écran plus explicite et lisible"],
  },

  {
    id: "browse-domiciles-in-places",
    label: "Inclure les lieux de domicile dans le circuit des lieux d'une personne",
    type: "todo",
    status: "in_progress",
    expectedAt: "2026-04-08",
    filePath: "src/features/family-tree/pages/FamilyTreeBrowsePage.tsx",
    category: "family-tree",
    priority: "medium",
  },
  {
    id: "browse-no-spouse-no-children-message",
    label: "Revoir le message 'pas de conjoint / d'enfant identifié'",
    type: "todo",
    status: "backlog",
    expectedAt: "2026-04-08",
    filePath: "src/features/family-tree/pages/FamilyTreeBrowsePage.tsx",
    category: "family-tree",
    priority: "medium",
    details: ["Distinguer absence d’identification et absence certaine"],
  },
  {
    id: "browse-reaction-override-photo",
    label: "Bouton 'C'est moi' : permettre d'override la photo affichée",
    type: "todo",
    status: "backlog",
    expectedAt: "2026-04-12",
    filePath: "src/features/family-tree/pages/FamilyTreeBrowsePage.tsx",
    category: "identity",
    priority: "high",
  },
  {
    id: "browse-reaction-labels",
    label: "Bouton 'C'est moi' : revoir les labels 'sur cette personne' / 'de lui'",
    type: "todo",
    status: "backlog",
    expectedAt: "2026-04-09",
    filePath: "src/features/family-tree/pages/FamilyTreeBrowsePage.tsx",
    category: "ux",
    priority: "medium",
  },
  {
    id: "browse-touched-panel",
    label: "Revoir le touched panel",
    type: "nice_to_have",
    status: "backlog",
    expectedAt: "2026-04-20",
    filePath: "src/features/family-tree/pages/FamilyTreeBrowsePage.tsx",
    category: "ux",
    priority: "low",
  },
  {
    id: "browse-force-refresh-me",
    label: "Forcer le refresh local après 'C'est moi' sans attendre un reload de page",
    type: "todo",
    status: "in_progress",
    expectedAt: "2026-04-06",
    filePath: "src/features/family-tree/pages/FamilyTreeBrowsePage.tsx",
    category: "identity",
    priority: "high",
    details: [
      "Afficher immédiatement les sections Réagir et Contribuer",
      "Éviter le refresh manuel",
    ],
  },
  {
    id: "browse-validation-mail-message",
    label: "Afficher le message : vous recevrez un mail quand le profil sera validé",
    type: "todo",
    status: "backlog",
    expectedAt: "2026-04-07",
    filePath: "src/features/family-tree/pages/FamilyTreeBrowsePage.tsx",
    category: "moderation",
    priority: "medium",
  },
  {
    id: "browse-claim-mail-notifications",
    label: "Envoyer des mails quand le profil est vérifié et quand une demande de vérification est faite",
    type: "todo",
    status: "backlog",
    expectedAt: "2026-04-15",
    filePath: "src/features/family-tree/pages/FamilyTreeBrowsePage.tsx",
    category: "notifications",
    priority: "high",
    details: ["Notification mail demande de vérification", "Notification mail profil vérifié"],
  },
  {
    id: "browse-report-issue-moderation",
    label: "Ajouter 'Signaler un manque / un souci' avec modération",
    type: "todo",
    status: "backlog",
    expectedAt: "2026-04-18",
    filePath: "src/features/family-tree/pages/FamilyTreeBrowsePage.tsx",
    category: "moderation",
    priority: "high",
    details: ["Workflow de modération", "Notification mail"],
  },
  {
    id: "browse-unmask-request",
    label: "Ajouter une demande de démasquage avec modération",
    type: "todo",
    status: "backlog",
    expectedAt: "2026-04-18",
    filePath: "src/features/family-tree/pages/FamilyTreeBrowsePage.tsx",
    category: "moderation",
    priority: "high",
    details: ["Workflow de modération", "Notification mail"],
  },
  {
    id: "browse-family-knowledge-overlay",
    label: "Créer un calque family-knowledge sur browse",
    type: "nice_to_have",
    status: "backlog",
    expectedAt: "2026-04-22",
    filePath: "src/features/family-tree/pages/FamilyTreeBrowsePage.tsx",
    category: "family-knowledge",
    priority: "medium",
  },
  {
    id: "browse-photo-replacement",
    label: "Permettre de proposer une photo pour remplacer celle affichée",
    type: "todo",
    status: "backlog",
    expectedAt: "2026-04-19",
    filePath: "src/features/family-tree/pages/FamilyTreeBrowsePage.tsx",
    category: "photos",
    priority: "high",
    details: ["Upload / proposition de remplacement", "Notification mail"],
  },
  {
    id: "browse-consent-delegation",
    label: "Gérer la délégation de consentement",
    type: "todo",
    status: "backlog",
    expectedAt: "2026-04-25",
    filePath: "src/features/family-tree/pages/FamilyTreeBrowsePage.tsx",
    category: "consent",
    priority: "high",
  },
  {
    id: "browse-hero-sheet-icon",
    label: "Ajouter la fiche + une icône dans le hero",
    type: "nice_to_have",
    status: "backlog",
    expectedAt: "2026-04-14",
    filePath: "src/features/family-tree/pages/FamilyTreeBrowsePage.tsx",
    category: "ux",
    priority: "low",
  },

  {
    id: "handle-profile-calc-functions",
    label: "Brancher les deux fonctions de calcul",
    type: "todo",
    status: "in_progress",
    expectedAt: "2026-04-04",
    filePath: "src/features/family-tree/pages/FamilyTreeHandleProfilePage.tsx",
    category: "analytics",
    priority: "high",
  },
  {
    id: "handle-profile-my-likes",
    label: "Afficher mes j'aime",
    type: "todo",
    status: "backlog",
    expectedAt: "2026-04-10",
    filePath: "src/features/family-tree/pages/FamilyTreeHandleProfilePage.tsx",
    category: "analytics",
    priority: "medium",
  },
  {
    id: "handle-profile-likes-given",
    label: "Afficher les j'aime que j'ai donnés",
    type: "todo",
    status: "backlog",
    expectedAt: "2026-04-10",
    filePath: "src/features/family-tree/pages/FamilyTreeHandleProfilePage.tsx",
    category: "analytics",
    priority: "medium",
  },
  {
    id: "handle-profile-unique-views",
    label: "Afficher le nombre de personnes individuelles qui se sont arrêtées sur ma fiche",
    type: "todo",
    status: "backlog",
    expectedAt: "2026-04-12",
    filePath: "src/features/family-tree/pages/FamilyTreeHandleProfilePage.tsx",
    category: "analytics",
    priority: "medium",
  },

  {
    id: "hub-labels-and-recommended",
    label: "Revoir les labels et les contenus recommandés pour commencer",
    type: "todo",
    status: "in_progress",
    expectedAt: "2026-04-06",
    filePath: "src/features/family-tree/pages/FamilyTreeHubPage.tsx",
    category: "ux",
    priority: "medium",
  },
  {
    id: "hub-story-guard",
    label: "Rendre family-tree/story disponible uniquement si default_gedcom_person_id + claim approved",
    type: "todo",
    status: "backlog",
    expectedAt: "2026-04-07",
    filePath: "src/features/family-tree/pages/FamilyTreeHubPage.tsx",
    category: "guard",
    priority: "high",
  },
];